//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odds_Grabber___sbobet.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ______odds_issend_01 {
            get {
                return ((bool)(this["______odds_issend_01"]));
            }
            set {
                this["______odds_issend_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ______odds_issend_02 {
            get {
                return ((bool)(this["______odds_issend_02"]));
            }
            set {
                this["______odds_issend_02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ______odds_iswaiting_01 {
            get {
                return ((bool)(this["______odds_iswaiting_01"]));
            }
            set {
                this["______odds_iswaiting_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ______odds_iswaiting_02 {
            get {
                return ((bool)(this["______odds_iswaiting_02"]));
            }
            set {
                this["______odds_iswaiting_02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ______is_send_telegram {
            get {
                return ((bool)(this["______is_send_telegram"]));
            }
            set {
                this["______is_send_telegram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sbobet.com/euro/football/england")]
        public string ______root_url {
            get {
                return ((string)(this["______root_url"]));
            }
            set {
                this["______root_url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.sbobet.com")]
        public string ______root_url_equals {
            get {
                return ((string)(this["______root_url_equals"]));
            }
            set {
                this["______root_url_equals"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sportdafa.net/en/sports-df/sports")]
        public string ______root_url_login {
            get {
                return ((string)(this["______root_url_login"]));
            }
            set {
                this["______root_url_login"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sbobet.com/en/data/event?ts=")]
        public string ______SBOBET_running {
            get {
                return ((string)(this["______SBOBET_running"]));
            }
            set {
                this["______SBOBET_running"] = value;
            }
        }
    }
}
